<?php
/**
 * Created by PhpStorm.
 * User: ubuntu
 * Date: 17/10/17
 * Time: 15:40
 */

/**
 * Form for uploading the "amapl funded" logo image.
 */
function amapl_trainings_settings_form() {
  // Logo
  $form['amapl_training_funded_logo'] = array(
    '#type' => 'fieldset',
    '#title' => t('Logo "Prise en charge amapl"'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  // If there is already an uploaded image, display the image here.
  if ($logo_fid = variable_get('amapl_training_funded_logo_fid', FALSE)) {
//    dpm($logo_fid);
    if ($image = file_load($logo_fid)) {
      $form['amapl_training_funded_logo']['image'] = array(
        '#markup' => theme('image_style',
          array(
            'style_name' => 'funded_logo',
            'path' => $image->uri,
            'alt' => 'Prise en charge partielle du financement par amapl pour les amapliens',
          )
        ),
      );
    }


  }
  $desc = t(
    'Logo que vous voulez afficher pour les formations prise en charge par amapl.<br/>' .
    'Dimensions minimales préconisées : largeur <b>48 px</b>, hauteur <b>48 px</b>.<br/>' .
    'Format préconisé : <b>carré</b>.'
    );
  $form['amapl_training_funded_logo']['amapl_training_funded_logo_fid'] = array(
    '#title' => t('Fichier'),
    '#type' => 'managed_file',
    '#description' => $desc,
    '#default_value' => variable_get('amapl_training_funded_logo_fid', ''),
    '#upload_location' => 'public://trainings',
  );

  return system_settings_form($form);
}