<?php
/**
 * @file
 * Code for the Atterrissage AGA feature.
 */

include_once 'atterrissage_aga.features.inc';

/**
* Implements hook_node_view().
 */
function atterrissage_aga_node_view($node, $view_mode, $langcode) {

  if(node_is_page($node) && $node->type == "atterrissage_aga") {

    if(isset($node->field_content_after_login)){
      /*dpm($node->field_content_after_login);*/
      if(user_is_logged_in()){
        drupal_goto('<front>');
      }
    }

  }
}
function atterrissage_aga_init() {
  $variables = json_encode($_POST);
  drupal_add_js('
  jQuery(function($){
    var para = ' . $variables . ';
    if(para.login && para.mdp){
      $("#edit-name").val(para.login);
      $("#edit-pass").val(para.mdp);
      $("#user-login-form").submit();
    }
  });
  ','inline');
}

/**
 * Implements hook_user_logout().
 */
function atterrissage_aga_user_logout($account) {
  drupal_set_message(t('Thanks for visiting, come again!'));
  global $user;
  $goto = '<front>';

  foreach ($user->roles as $role){
    switch ($role) {
      case 'AGAKAM':
        $goto = ('http://www.agakam.com');
        break;
      case 'Import ADH':
        $goto = ('http://www.amapl.com');
        break;
      case 'Import COR':
        $goto = ('http://www.amapl.com');
        break;
      case 'AGA08':
        $goto = ('http://www.aga08.fr');
        break;
      case 'AGAPROFIL':
        $goto = ('http://www.agaprofil.fr');
        break;
      case 'AGCS':
        $goto = ('https://www.agcs-omga.fr');
        break;
      case 'AMAPL':
        $goto = ('http://www.amapl.com');
        break;
      case 'ANGIIL':
        $goto = ('http://www.angiil.com');
        break;
      case 'AGADOM':
        $goto = ('http://www.agadom.org');
        break;
      case 'AGMPS BEARN':
        $goto = ('http://www.vigipl.com/agmps');
        break;
        case 'AA MEDECINS':
        $goto = ('http://www.aamedecins.fr');
        break;
      case 'DEMO':
        $goto = ('/demo/');
        break;
    }
    if ($goto != '<front>') break;
  }

  session_destroy();
  drupal_goto($goto);
}
