<?php
/**
 * @file
 * Drupal needs this blank file.
 */
/**
 * Implements hook_node_view().
 */
function yd_add_js_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'event' && $view_mode == 'full') {
    drupal_add_js(drupal_get_path('module','yd_add_js') . '/js/lightbox/jquery.lightbox_me.js');
    drupal_add_js(drupal_get_path('module','yd_add_js') . '/js/show-registration.js');
  }
}
