<?php
/**
 * @file
 * AGA user import.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function aga_user_import_form_migrate_ui_migrate_group_alter(&$form, &$form_state, $form_id) {
  $roles = _aga_import_variants();
  $key = key($roles);
  if (!empty($form['dashboard']['migrations']['#options']['AgaUserMigration' . ucfirst($key)])) {
    $form['operations']['options']['update_fake'] = $form['operations']['options']['update'];
    $form['operations']['options']['update_fake']['#default_value'] = TRUE;
    $form['operations']['options']['update_fake']['#disabled'] = TRUE;
    $form['operations']['options']['update_fake']['#weight'] = -1;

    $form['operations']['options']['update']['#type'] = 'value';
    $form['operations']['options']['update']['#value'] = TRUE;

    array_unshift($form['operations']['submit']['#submit'], '_aga_user_import_kill_flag');
  }
}

function _aga_user_import_kill_flag($form, &$form_state) {
  if ($form_state['values']['operation'] != 'import_immediate') {
    return;
  }

  $migrations = _migrate_ui_selected_migrations($form_state['values']);
  foreach ($migrations as $machine_name) {
    $migration = Migration::getInstance($machine_name);
    if ($migration->getStatus() != MigrationBase::STATUS_IMPORTING) {
      variable_del('aga_user_import_first_run_' . get_class($migration));
    }
  }
}

/**
 * Implements hook_cron().
 */
function aga_user_import_cron() {
  // Get AGA user roles rids.
  $rids= _aga_user_roles_rids();

  // Get users of these roles that are disabled.
  $query = db_select('users_roles', 'ur');
  $query->join('users', 'u', 'ur.uid = u.uid');
  $query->fields('u', array('uid'))
    ->condition('ur.rid', $rids)
    ->condition('u.status', 0);
  $uids = $query->execute()->fetchCol();

  // Delete those users.
  user_delete_multiple($uids);
}

/**
 * Implements hook_help().
 */
function aga_user_import_help($path, $arg) {
  switch ($path) {
    case 'admin/content/migrate':
      return '<p>Pour accéder aux deux imports ADH et COR, cliquez sur le lien "' . l('AGA Imports', 'admin/content/migrate/groups/aga') . '" dans la colonne "Groupe".</p>';

    case 'admin/content/migrate/groups/%':
      if ($arg[4] == 'aga') {
        return '<p>Les fichiers source doivent être déposés dans le répertoire <b>' . conf_path() . '/data</b> et s\'appeler <b>ADH.csv</b> ou <b>COR.csv</b> selon l\'import à effectuer.</p>';
      }
  }
}

// -----------------------------------------------------------------------------
// Helpers.

function _aga_import_variants() {
  return array(
    'adh' => array(
      'label'        => 'Import ADH',
      'machine_name' => 'import_adh',
      'rid'          => _aga_user_role_rid('import_adh'),
      'filename'     => 'ADH.csv',
    ),
    'cor' => array(
      'label'        => 'Import COR',
      'machine_name' => 'import_cor',
      'rid'          => _aga_user_role_rid('import_cor'),
      'filename'     => 'COR.csv',
    ),
  );
}

/**
 * Get AGA user roles rids.
 *
 * @return array
 */
function _aga_user_roles_rids() {
  $roles = _aga_import_variants();
  $rids= array();
  foreach ($roles as $role) {
    $rids[] = $role['rid'];
  }
  return $rids;
}

/**
 * Helper to convert role name in a machine name.
 *
 * Copied from role_export to maintain compatibility.
 *
 * @param $name
 * @return mixed
 */
function _aga_user_role_machine_name($name) {
  return str_replace(' ', '_', strtolower($name));
}

/**
 * Helper to convert role machine_name in a unique rid.
 *
 * Copied from role_export to maintain compatibility.
 *
 * @param $machine_name
 * @return int
 */
function _aga_user_role_rid($machine_name) {
  $hash = md5($machine_name);
  $shorter = substr($hash, -7);
  $number = hexdec($shorter);
  return (int) $number;
}
