<?php
/**
 * @file
 * AGA user import.
 */

/**
 * Implements hook_cron().
 */
function aga_user_import_cron() {
  // Get AGA user roles rids.
  $rids= _aga_user_roles_rids();

  // Get users of these roles that are disabled.
  $query = db_select('users_roles', 'ur');
  $query->join('users', 'u', 'ur.uid = u.uid');
  $query->fields('u', array('uid'))
    ->condition('ur.rid', $rids)
    ->condition('u.status', 0);
  $uids = $query->execute()->fetchCol();

  // Delete those users.
  user_delete_multiple($uids);
}

/**
 * Implements hook_help().
 */
function aga_user_import_help($path, $arg) {
  switch ($path) {
    case 'admin/content/migrate':
      return '<p>Pour accéder aux deux imports ADH et COR, cliquez sur le lien "' . l('AGA Imports', 'admin/content/migrate/groups/aga') . '" dans la colonne "Groupe".</p>';

    case 'admin/content/migrate/groups/%':
      if ($arg[4] == 'aga') {
        return '<p>Les fichiers source doivent être déposés dans le répertoire <b>' . conf_path() . '/data</b> et s\'appeler <b>ADH.csv</b> ou <b>COR.csv</b> selon l\'import à effectuer.<br />Ces fichiers seront détruits à la fin du processus afin de garantir la sécurité des données.</p>';
      }
  }
}

// -----------------------------------------------------------------------------
// Helpers.

function _aga_import_variants() {
  return array(
    'adh' => array(
      'label'        => 'Import ADH',
      'machine_name' => 'import_adh',
      'rid'          => _aga_user_role_rid('import_adh'),
      'filename'     => 'ADH.csv',
    ),
    'cor' => array(
      'label'        => 'Import COR',
      'machine_name' => 'import_cor',
      'rid'          => _aga_user_role_rid('import_cor'),
      'filename'     => 'COR.csv',
    ),
  );
}

/**
 * Get AGA user roles rids.
 *
 * @return array
 */
function _aga_user_roles_rids() {
  $roles = _aga_import_variants();
  $rids= array();
  foreach ($roles as $role) {
    $rids[] = $role['rid'];
  }
  return $rids;
}

/**
 * Helper to convert role name in a machine name.
 *
 * Copied from role_export to maintain compatibility.
 *
 * @param $name
 * @return mixed
 */
function _aga_user_role_machine_name($name) {
  return str_replace(' ', '_', strtolower($name));
}

/**
 * Helper to convert role machine_name in a unique rid.
 *
 * Copied from role_export to maintain compatibility.
 *
 * @param $machine_name
 * @return int
 */
function _aga_user_role_rid($machine_name) {
  $hash = md5($machine_name);
  $shorter = substr($hash, -7);
  $number = hexdec($shorter);
  return (int) $number;
}
