<?php
/**
 * @file
 * Code for the Atterrissage AGA feature.
 */

include_once 'atterrissage_aga.features.inc';

/**
* Implements hook_node_view().
 */
function atterrissage_aga_node_view($node, $view_mode, $langcode) {

  if(node_is_page($node) && $node->type == "atterrissage_aga") {

    if(isset($node->field_content_after_login)){
      /*dpm($node->field_content_after_login);*/
      if(user_is_logged_in()){
        dpm('connecté');
        drupal_goto('<front>');
      }else{
        dpm('non connecté');
      }

      //drupal_goto('<front>');
    }

  }
}
function atterrissage_aga_init() {
  $variables = json_encode($_POST);
  drupal_add_js('
  jQuery(function($){
    var para = ' . $variables . ';
    if(para.login && para.mdp){
      $("#edit-name").val(para.login);
      $("#edit-pass").val(para.mdp);
      $("#user-login-form").submit();
    }
  });
  ','inline');
}
