<?php
/**
 * @file
 * feature_artist_gallery.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function feature_artist_gallery_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "ds" && $api == "ds") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function feature_artist_gallery_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_node_info().
 */
function feature_artist_gallery_node_info() {
  $items = array(
    'galerie_adherents' => array(
      'name' => t('Galerie d\'adhérents'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}
